export interface PreOperatorio {
  agendamento_Id: number,
  atendimento_Id: number,
  animal_Id: number,
  veterinario_Id: number,
  tutor_Id: number,

  jejum: boolean,
  ultimaAlimentacao: string,
  ultimaIngestaoLiquidos: string,
  presoDuranteNoite: boolean,
  soltoDuranteNoite: boolean,
  horarioPreso?: string,
  urinandoNormalmente: boolean,
  antiCio: boolean,
  ultimaAplicacao?: string,
  cioRecente: boolean,
  quandoCruzou?: string,
  filhoteRecente: boolean,
  idadeFilhote?: number,
  historicoVeterinario: boolean,
  tratamentoCirurgico: boolean,
  quandoTratamentoCirurgico?: string,
  observacoesComportamento: string,
  historicoDoencas: boolean,
  criseEpileptica: boolean,
  desmaios: boolean,
  vermifugado: boolean
}
